// SPDX-FileCopyrightText: 2021 Rifat Hasan <atunutemp1@gmail.com>
//
// SPDX-License-Identifier: MIT

#ifndef DBMANAGER_H
#define DBMANAGER_H

#include <QtSql>

class DBManager : public QObject {
	Q_OBJECT
public:
	explicit DBManager(QObject* parent = nullptr);

	QVariant addCategory(QString name);
	QVariant addPlatform(QString name);
	QVariant addRole(QString name, QString description);

	QStringList getCategoryList();

private:
	const QLatin1String SOFTWARE_TABLE_SQL = QLatin1String(R"(
		CREATE TABLE IF NOT EXISTS SOFTWARE(
			ID INTEGER PRIMARY KEY,
			NAME TEXT NOT NULL,
			LIMITATION TEXT,
			URL TEXT,
			NOTES TEXT
		)
	)");

	const QLatin1String CATEGORY_TABLE_SQL = QLatin1String(R"(
		CREATE TABLE IF NOT EXISTS CATEGORY(
			ID INTEGER PRIMARY KEY,
			NAME TEXT NOT NULL
		)
	)");

	const QLatin1String PLATFORM_TABLE_SQL = QLatin1String(R"(
		CREATE TABLE IF NOT EXISTS PLATFORM(
			ID INTEGER PRIMARY KEY,
			NAME TEXT NOT NULL
		)
	)");

	const QLatin1String PREFERENCE_ROLE_TABLE_SQL = QLatin1String(R"(
		CREATE TABLE IF NOT EXISTS PREFERENCE_ROLE(
			ID INTEGER PRIMARY KEY,
			NAME TEXT NOT NULL,
			DESCRIPTION TEXT NOT NULL
		)
	)");

	const QLatin1String REQUIREMENT_TABLE_SQL = QLatin1String(R"(
		CREATE TABLE IF NOT EXISTS REQUIREMENT(
			ID INTEGER PRIMARY KEY,
			NAME TEXT NOT NULL,
			CATEGORY_ID INTEGER NOT NULL,
			FOREIGN KEY (CATEGORY_ID)
				REFERENCES CATEGORY (ID)
				ON DELETE CASCADE
				ON UPDATE CASCADE
		)
	)");

	const QLatin1String SOFTWARE_CATEGORY_TABLE_SQL = QLatin1String(R"(
		CREATE TABLE IF NOT EXISTS SOFTWARE_CATEGORY(
			SOFTWARE_ID INTEGER,
			CATEGORY_ID INTEGER,
			PRIMARY KEY (SOFTWARE_ID, CATEGORY_ID),
			FOREIGN KEY (SOFTWARE_ID)
				REFERENCES SOFTWARE (ID)
				ON DELETE CASCADE
				ON UPDATE CASCADE,
			FOREIGN KEY (CATEGORY_ID)
				REFERENCES CATEGORY (ID)
				ON DELETE CASCADE
				ON UPDATE CASCADE
		)
	)");

	const QLatin1String SOFTWARE_PLATFORM_TABLE_SQL = QLatin1String(R"(
		CREATE TABLE IF NOT EXISTS SOFTWARE_PLATFORM(
			SOFTWARE_ID INTEGER,
			PLATFORM_ID INTEGER,
			PRIMARY KEY (SOFTWARE_ID, PLATFORM_ID),
			FOREIGN KEY (SOFTWARE_ID)
				REFERENCES SOFTWARE (ID)
				ON DELETE CASCADE
				ON UPDATE CASCADE,
			FOREIGN KEY (PLATFORM_ID)
				REFERENCES PLATFORM (ID)
				ON DELETE CASCADE
				ON UPDATE CASCADE
		)
	)");

	const QLatin1String SOFTWARE_REQUIREMENT_TABLE_SQL = QLatin1String(R"(
		CREATE TABLE IF NOT EXISTS SOFTWARE_REQUIREMENT(
			SOFTWARE_ID INTEGER,
			REQUIREMENT_ID INTEGER,
			PRIMARY KEY (SOFTWARE_ID, REQUIREMENT_ID),
			FOREIGN KEY (SOFTWARE_ID)
				REFERENCES SOFTWARE (ID)
				ON DELETE CASCADE
				ON UPDATE CASCADE,
			FOREIGN KEY (REQUIREMENT_ID)
				REFERENCES REQUIREMENT (ID)
				ON DELETE CASCADE
				ON UPDATE CASCADE
		)
	)");

	const QLatin1String CAT_PLAT_SOFT_ROLE_TABLE_SQL = QLatin1String(R"(
		CREATE TABLE IF NOT EXISTS CAT_PLAT_SOFT_ROLE(
			CATEGORY_ID INTEGER,
			PLATFORM_ID INTEGER,
			SOFTWARE_ID INTEGER,
			ROLE_ID INTEGER,
			PRIMARY KEY (CATEGORY_ID, PLATFORM_ID, SOFTWARE_ID, ROLE_ID),
			FOREIGN KEY (CATEGORY_ID)
				REFERENCES CATEGORY (ID)
				ON DELETE CASCADE
				ON UPDATE CASCADE,
			FOREIGN KEY (PLATFORM_ID)
				REFERENCES PLATFORM (ID)
				ON DELETE CASCADE
				ON UPDATE CASCADE,
			FOREIGN KEY (SOFTWARE_ID)
				REFERENCES SOFTWARE (ID)
				ON DELETE CASCADE
				ON UPDATE CASCADE,
			FOREIGN KEY (ROLE_ID)
				REFERENCES PREFERENCE_ROLE (ID)
				ON DELETE CASCADE
				ON UPDATE CASCADE
		)
	)");

	const QLatin1String INSERT_SOFTWARE_SQL = QLatin1String(R"(
		INSERT INTO SOFTWARE (NAME, LIMITATION, URL, NOTES)
		VALUES(?, ?, ?, ?)
	)");

	const QLatin1String INSERT_CATEGORY_SQL = QLatin1String(R"(
		INSERT INTO CATEGORY (NAME)
		VALUES(?)
	)");

	const QLatin1String INSERT_PLATFORM_SQL = QLatin1String(R"(
		INSERT INTO PLATFORM (NAME)
		VALUES(?)
	)");

	const QLatin1String INSERT_ROLE_SQL = QLatin1String(R"(
		INSERT INTO PREFERENCE_ROLE (NAME, DESCRIPTION)
		VALUES(?, ?)
	)");

	const QLatin1String INSERT_REQUIREMENT_SQL = QLatin1String(R"(
		INSERT INTO REQUIREMENT (NAME, CATEGORY_ID)
		VALUES(?, ?)
	)");

	const QLatin1String INSERT_SOFTWARE_CATEGORY_SQL = QLatin1String(R"(
		INSERT INTO SOFTWARE_CATEGORY (SOFTWARE_ID, CATEGORY_ID)
		VALUES(?, ?)
	)");

	const QLatin1String INSERT_SOFTWARE_PLATFORM_SQL = QLatin1String(R"(
		INSERT INTO SOFTWARE_PLATFORM (SOFTWARE_ID, PLATFORM_ID)
		VALUES(?, ?)
	)");

	const QLatin1String INSERT_SOFTWARE_REQUIREMENT_SQL = QLatin1String(R"(
		INSERT INTO SOFTWARE_REQUIREMENT (SOFTWARE_ID, REQUIREMENT_ID)
		VALUES(?, ?)
	)");

	const QLatin1String INSERT_CAT_PLAT_SOFT_ROLE_SQL = QLatin1String(R"(
		INSERT INTO CAT_PLAT_SOFT_ROLE (CATEGORY_ID, PLATFORM_ID, SOFTWARE_ID, ROLE_ID)
		VALUES(?, ?, ?, ?)
	)");

	QSqlQuery insertSoftwareQuery,
		insertCategoryQuery,
		insertPlatformQuery,
		insertRoleQuery,
		insertRequirementQuery,
		insertSoftwareCategoryQuery,
		insertSoftwarePlatformQuery,
		insertSoftwareRequirementQuery,
		insertCatPlatSoftRoleQuery;

	QSqlError createTables();
	QSqlError prepareStatements(QSqlDatabase& db);

	/**
	 * @brief Populate database with default data. If relevant data
	 * already exists, it won't modify the DB. 
	 */
	void populateDB();
};

#endif // DBMANAGER_H
